=== PolySim/IS2A/S6/automate/sujet3/contactsBis.dtd
<!ELEMENT contacts (contact+)>
        <!ELEMENT contact (identité, addresse, email+)>
        <!ELEMENT identité (nom, prénom, date_naissance)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prénom (#PCDATA)>
        <!ELEMENT date_naissance (#PCDATA)>
        <!ELEMENT addresse (rue, ville, pays)>
        <!ELEMENT rue EMPTY>
        <!ATTLIST rue numéro CDATA #IMPLIED
                nom CDATA #REQUIRED>
        <!ELEMENT ville EMPTY>
        <!ATTLIST ville code_postal NMTOKEN #REQUIRED
                nom CDATA #REQUIRED>
        <!ELEMENT pays (#PCDATA)>
        <!ELEMENT email (#PCDATA)>

=== PolySim/IS2A/S6/automate/sujet3/contactsBis.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE contacts SYSTEM "contactsBis.dtd">
<contacts>
    <contact>
        <identité>
            <nom>Blanquaert</nom>
            <prénom>Jacques</prénom>
            <date_naissance>23/10/2002</date_naissance>
        </identité>
        <addresse>
            <rue nom="rue du Vert Pré" numéro="27"/>
            <ville code_postal="59100" nom="Roubaix"/>
            <pays>France</pays>
        </addresse>
        <email>jblanquaert@sfr.fr</email>
        <email>jblanquaert@gmail.com</email>
    </contact>
    <contact>
        <identité>
            <nom>Giraud</nom>
            <prénom>Sophie</prénom>
            <date_naissance>13/08/2001</date_naissance>
        </identité>
        <addresse>
            <rue nom="123B Rue du vert Pré"/>
            <ville code_postal="69000" nom="Lyon"/>
            <pays>France</pays>
        </addresse>
        <email>sosogiraud@hotmail.com</email>
    </contact>
</contacts>
