=== PolySim/IS2A/S6/automate/sujet3/contactsV1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="contacts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="contact">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identité"/>
				<xs:element name="email" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="identité">
		<xs:complexType>
			<xs:sequence>	
				<xs:element name="nom" type="xs:string"/>
				<xs:element name="prénom" type="xs:string"/>
				<xs:element name="date_naissance" type="xs:date"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== PolySim/IS2A/S6/automate/sujet3/contactsV1_4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="contactsV1.xsd">
    <contact>
        <identité>
            <nom>Blanquaert</nom>
            <prénom>Jacques</prénom>
            <date_naissance>2022-10-23</date_naissance>
        </identité>
        <email>jblanquaert@sfr.fr</email>
    </contact>
    <contact>
        <identité>
            <nom>Giraud</nom>
            <prénom>Sophie</prénom>
            <date_naissance>2001-08-13</date_naissance>
        </identité>
    </contact>
    <contact>
        <identité>
            <nom>Dupont</nom>
            <prénom>Jean</prénom>
            <date_naissance>2001-06-01</date_naissance>
        </identité>
        <email>jeandudu@orange.fr</email>
    </contact>
</contacts>
